# Libraries and session info

Here we load libraries, create a folder for saving figures and define global variables. Note that this part of code is needed for the remaining code to run. 

```{r load-libraries, message=FALSE}
library(knitr)
library(bookdown)
library(VennDiagram) 
library(Rmisc)

library(tidyverse)
library(patchwork)
library(ggpubr)
library(kableExtra)
library(BayesFactor)
library(afex)

source("function/TES.R")

# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

# check if figure folder exists, if not, create a new one
if(!dir.exists("figure")){
  dir.create("figure")
}

# Suppress summarize info
options(dplyr.summarise.inform = FALSE)

# set the theme to theme_bw() for all ggplot2 figures
# and put the figure legend on top of the figure, in a horizontal direction
theme_set(theme_bw() +
            theme(legend.position = "top",
                  legend.direction = "horizontal"))

# use colorblind friendly colors
color_values <- c("#56B4E9", "#E69F00")

# size of the shapes in the figures
shape_size <- 2.5

# dodge width
dodge_width <- 0.35
```


```{r session-info}
sessionInfo()
```

